inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rake'
    - 'lib/**/*.rb'
  Exclude:
    # - 'spec/**/*'
    - 'db/*.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/ClassLength:
   Max: 350

Metrics/BlockLength:
  Max: 70

Metrics/AbcSize:
  Enabled: false

Style/ClassVars:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Layout/IndentationWidth:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false










